{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"err":{"message":"Validation error","name":"SequelizeUniqueConstraintError","stack":"Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.insert (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:795:21)\n    at async Professional.save (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:4154:35)\n    at async Function.create (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:2305:12)\n    at async create (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\professionalRepository.ts:6:12)\n    at async createProfessional (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\professionalService.ts:7:29)\n    at async create (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\professionalContrller.ts:10:33)"},"msg":"Validation error","time":"2025-10-29T00:29:23.610Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al obtener servicios: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\serviceRepository.ts:10:12)\n    at async getAllServices (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\serviceService.ts:12:22)\n    at async getAllServices (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\serviceController.ts:34:26) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'professional_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'professional_id' in 'field list'\",\n    sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n    parameters: undefined\n  },\n  original: Error: Unknown column 'professional_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'professional_id' in 'field list'\",\n    sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n    parameters: undefined\n  },\n  sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n  parameters: {}\n}","time":"2025-10-29T00:32:11.699Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al obtener servicios: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\serviceRepository.ts:10:12)\n    at async getAllServices (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\serviceService.ts:12:22)\n    at async getAllServices (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\serviceController.ts:34:26) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'professional_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'professional_id' in 'field list'\",\n    sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n    parameters: undefined\n  },\n  original: Error: Unknown column 'professional_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'professional_id' in 'field list'\",\n    sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n    parameters: undefined\n  },\n  sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n  parameters: {}\n}","time":"2025-10-29T00:32:20.297Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al obtener servicios: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\serviceRepository.ts:10:12)\n    at async getAllServices (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\serviceService.ts:12:22)\n    at async getAllServices (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\serviceController.ts:34:26) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'professional_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'professional_id' in 'field list'\",\n    sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n    parameters: undefined\n  },\n  original: Error: Unknown column 'professional_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'professional_id' in 'field list'\",\n    sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n    parameters: undefined\n  },\n  sql: 'SELECT `id`, `id_professional` AS `idProfessional`, `name`, `description`, `price`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `professional_id` AS `professionalId` FROM `services` AS `Service`;',\n  parameters: {}\n}","time":"2025-10-29T00:32:39.548Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al crear turno en service: Error: La fecha del turno debe ser futura\n    at Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:14:13)\n    at createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:53)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:435:11)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:295:15\n    at processParams (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:582:12)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:291:5)","time":"2025-10-29T00:34:59.964Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error en createAppointment controller: Error: La fecha del turno debe ser futura\n    at Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:14:13)\n    at createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:53)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:435:11)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:295:15\n    at processParams (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:582:12)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:291:5)","time":"2025-10-29T00:34:59.965Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al crear turno en service: Error: La fecha del turno debe ser futura\n    at Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:14:13)\n    at createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:53)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:435:11)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:295:15\n    at processParams (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:582:12)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:291:5)","time":"2025-10-29T00:37:01.093Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error en createAppointment controller: Error: La fecha del turno debe ser futura\n    at Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:14:13)\n    at createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:53)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:435:11)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:295:15\n    at processParams (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:582:12)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:291:5)","time":"2025-10-29T00:37:01.093Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al verificar disponibilidad en repository: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:37:43.937Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al crear turno en service: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:37:43.937Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error en createAppointment controller: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:37:43.942Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al verificar disponibilidad en repository: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:38:01.296Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al crear turno en service: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:38:01.297Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error en createAppointment controller: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:38:01.300Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error en createAppointment controller: Error: El campo idUser es requerido\n    at Object.validateAppointmentInput (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:94:13)\n    at createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:9:24)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:435:11)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:295:15\n    at processParams (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:582:12)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:291:5)","time":"2025-10-29T00:38:43.637Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error en createAppointment controller: Error: El campo idService es requerido\n    at Object.validateAppointmentInput (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:94:13)\n    at createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:9:24)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:435:11)\n    at Layer.handleRequest (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\lib\\layer.js:152:17)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:295:15\n    at processParams (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:582:12)\n    at next (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\router\\index.js:291:5)","time":"2025-10-29T00:38:55.214Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al verificar disponibilidad en repository: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:39:04.043Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error al crear turno en service: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:39:04.044Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":6564,"level":50,"msg":"Error en createAppointment controller: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.select (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:1001:12)\n    at async Function.findAll (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1824:21)\n    at async Function.findOne (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1998:12)\n    at async Object.checkTimeAvailability (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\appointmentRepository.ts:130:33)\n    at async Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:18:25)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  original: Error: Unknown column 'user_id' in 'field list'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_FIELD_ERROR',\n    errno: 1054,\n    sqlState: '42S22',\n    sqlMessage: \"Unknown column 'user_id' in 'field list'\",\n    sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n    parameters: undefined\n  },\n  sql: \"SELECT `id`, `id_user` AS `idUser`, `id_service` AS `idService`, `date`, `time`, `phone`, `petname`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt`, `user_id` AS `userId`, `service_id` AS `serviceId` FROM `shifts` AS `Appointment` WHERE `Appointment`.`date` = '2025-11-25' AND `Appointment`.`time` = '15:30' AND `Appointment`.`id_service` = '6961e1bb-b200-4273-985e-c0d7c81d90a1' LIMIT 1;\",\n  parameters: {}\n}","time":"2025-10-29T00:39:04.058Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":15732,"level":50,"msg":"Error al crear turno en service: Error: El horario seleccionado no está disponible\n    at Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:25:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28)","time":"2025-10-29T22:13:55.158Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":15732,"level":50,"msg":"Error en createAppointment controller: Error: El horario seleccionado no está disponible\n    at Object.createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\appointmentService.ts:25:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async createAppointment (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\appointmentController.ts:12:28)","time":"2025-10-29T22:13:55.159Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":15932,"level":50,"msg":"Error al crear turno en service: Error: El horario seleccionado no está disponible\n    at Object.createShift (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\shiftService.ts:25:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async createShift (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\shiftController.ts:12:22)","time":"2025-10-29T22:24:15.651Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":15932,"level":50,"msg":"Error en createShift controller: Error: El horario seleccionado no está disponible\n    at Object.createShift (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\shiftService.ts:25:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async createShift (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\shiftController.ts:12:22)","time":"2025-10-29T22:24:15.651Z","v":0}
